moveit_manage_controllers: false
moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager
moveit_simple_controller_manager:
  controller_names:
  - xarm6_traj_controller
  xarm6_traj_controller:
    action_ns: follow_joint_trajectory
    default: true
    joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
    type: FollowJointTrajectory
trajectory_execution.allowed_execution_duration_scaling: 1.2
trajectory_execution.allowed_goal_duration_margin: 0.5
trajectory_execution.allowed_start_tolerance: 0.01
trajectory_execution.execution_duration_monitoring: false
plan_execution.record_trajectory_state_frequency: 10.0